name: IntraJ Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }} # Testing on MacOS and Ubuntu
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl
            COMPILER: gcc
            LINKER: gcc
    permissions:
      contents: read
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
     
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Build with Gradle
        run: ./gradlew clean build
